name: vdtube
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  http: ^1.2.2
  loading_animation_widget: ^1.3.0
  flutter_secure_storage: ^9.2.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  intl: ^0.20.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  typewritertext: ^3.0.9
  confetti: ^0.8.0
  # flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/vdTube.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/